[SETTINGS]
$ALLOW_FOREIGN_THREADS = True
$enhanced_edit          all
$putmess_logfile = Run3gdist.log
$variation=maale_library
$language=HEB
$enhanced_edit=all
$keyboard=MSWINX_1255
$display=MSWIN3_1255
$def_charset=cp1255
$sys_charset=cp1255
;$one_byte_storage=5,6
$rtl_application
$no_lmk_null
; $no_unifields should be set to 0 in idf environment
;$no_unifields=0
$no_unifields
$trace_is_true
;242,242,242
$active_field (col = 0)
$validation=limited
$STOP_ON_DIV_BY_ZERO = FALSE
$century_break=55
;$LICENSE_OPTIONS=LM_LICENSE_FILE=N:\one1\lic_file\license_95_07162012.xml,LM_NOTIFICATION=off
;$LICENSE_OPTIONS=LM_LICENSE_FILE=7166@100.100.100.36;7166@erpfs
$LICENSE_OPTIONS=LM_LICENSE_FILE=N:\one1\lic_file\01-sep-2021.XML,LM_NOTIFICATION=off
$SEARCH_OBJECT=file_only
$search_descriptor file_only
$NEWLINE=CR
$NO_VALREP_CHECK

#FILE N:\one1\uni3gdist\asn\RUN3Gdist_template.asn


;[FILES]
;usys:usys*.frm          usys:usys*.frm
;usys:usys*.svc          usys:usys*.svc
;usys:usys*.usp          usys:usys*.usp
;usys:usys*.dsp          usys:usys*.dsp
;usys:usys*.jss          usys:usys*.jss
;usys:usys*.dis          usys:usys*.dis
;usys:usys*.dsc          usys:usys*.dsc
;usys:userver.aps        usys:userver.aps
;ulibrary.chm      usysuniface:doc\ulibrary.chm

;*.frm n:\one1\uni3gdist\FRM\*.frm
;*.log n:\one1\3glog\*.log
;*.p*  n:\one1\3g9spl\*.p*
;*.svc n:\one1\uni3gdist\svc\*.svc
;*.aps n:\one1\uni3gdist\aps\*.aps

;$trace_is_true=1
;;$SEARCH_OBJECTS=dbms_first

;usys:uobj.dol n:\one1\uni3gdist\dol\maale3G1.dol
;usys:udesc.urr n:\one1\uni3gdist\urr\maale3G1.urr

;;#file usysadm:dbms.asn

[DRIVER_SETTINGS]
;usys$ora_params =dc, ss 10, fa, oc 250, 
usys$ora_params =dc, ss 10, fa, oc 250, dhfr,dri,dpa,u4_compatibility
ORA=U6.2
SOP=2.0


[PATHS]
;$PATH2 ORA:3gdist|uniface|uniface9
$PATH1 ORA:?|onenx|poly123



$IDF $PATH1
$UUU $PATH1
$SYS $PATH1

$DEF $PATH1
$ORA $PATH1
$NUM $PATH1

$com = com:

[ENTITIES]
numr_used.maale $NUM:numr_used.*
rngs.maale 	$NUM:rngs.*
numr_logger.maale $NUM:numr_logger.*   

[LOGICALS]
set_def_printer=F

[USER_3GL]
irtl.dll
n:\one1\uni3gdist\dll\OcxSyncBridge.dll
n:\one1\uni3gdist\dll\OcxBufferedSyncBridge.dll
n:\one1\uni3gdist\dll\reg.dll
n:\one1\uni3gdist\dll\bomc.dll
n:\one1\uni3gdist\dll\xf.dll
n:\one1\uni3gdist\dll\fh.dll
n:\one1\uni3gdist\dll\ff.dll
n:\one1\uni3gdist\dll\AUC.dll
n:\one1\uni3gdist\dll\crl.dll
n:\one1\uni3gdist\dll\AUD.dll
n:\one1\uni3gdist\dll\credit1.dll
n:\one1\uni3gdist\dll\bd32.dll
n:\one1\uni3gdist\dll\sog.dll
n:\one1\uni3gdist\dll\revltn.dll


